create extension if not exists "pgcrypto";

create table if not exists public.questionnaires (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  age text not null,
  gender text not null,
  faculty_of_study text not null,
  digital_devices text[] not null default '{}',
  digital_devices_other text,
  consecutive_hours text,
  screen_viewing_distance text,
  regular_breaks text,
  breaks_frequency text,
  eye_strain_reduction text[] not null default '{}',
  lighting_conditions text,
  screen_position text,
  sitting_posture text,
  chair_support text,
  neck_bending_frequency text,
  device_holding_position text,
  visual_symptoms text[] not null default '{}',
  visual_symptoms_score integer not null default 0,
  ocular_surface_symptoms text[] not null default '{}',
  ocular_surface_score integer not null default 0,
  extra_ocular_symptoms text[] not null default '{}',
  extra_ocular_score integer not null default 0,
  symptoms_frequency text,
  associated_with_screen_use text,
  eye_conditions text[] not null default '{}',
  corrective_lenses text,
  academic_year text,
  average_screen_time text,
  device_use_before_sleep text,
  sleep_hours text,
  eye_drops_usage text,
  eye_drops_frequency text,
  productivity_impact text,
  consulted_eye_care text,
  changed_study_habits text,
  study_habit_changes_description text,
  study_habit_changes_list text[] not null default '{}',
  study_habit_frequency text,
  study_habit_association text,
  study_habit_apply_frequency text,
  study_habit_help_level text,
  total_score integer not null default 0,
  submit_confirmation boolean not null default true
);

alter table public.questionnaires
  add column if not exists digital_devices_other text,
  add column if not exists sitting_posture text,
  add column if not exists chair_support text,
  add column if not exists neck_bending_frequency text,
  add column if not exists device_holding_position text,
  add column if not exists eye_conditions text[] not null default '{}',
  add column if not exists device_use_before_sleep text,
  add column if not exists academic_year text,
  add column if not exists average_screen_time text,
  add column if not exists study_habit_changes_list text[] not null default '{}',
  add column if not exists study_habit_frequency text,
  add column if not exists study_habit_association text,
  add column if not exists study_habit_apply_frequency text,
  add column if not exists study_habit_help_level text;

create index if not exists questionnaires_created_at_idx
  on public.questionnaires (created_at desc);